// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wapbkwuaojxgjtutersy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcGJrd3Vhb2p4Z2p0dXRlcnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTg1NDUsImV4cCI6MjA3MTE5NDU0NX0.o_Rg-ioZUv5ED_JcPWGVA7tVk6wGuwMB2FFR93YBfEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});